### PR TITLE
fixing example w/ unnamed arguments

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
I tried to follow, but the README seemed a little out of date, hopefully the changes here will fix that.

### CODE REVIEW

**Comment by ColinFay** [comment]
Thanks a lot! 

And glad to hear you found it useful :)

**Comment by ColinFay** [comment]
Hey @EmilHvitfeldt 

Unfortunately after trying your examples, it seems that they do not work :/ 

+ The `Craneur` R6 Object is exported out of the `{craneur}` 📦, so you should have to use the `:::` to access it 
+  The `add_package` does not take any argument (https://github.com/ColinFay/craneur/blob/master/R/R6.R#L42) and the name is created by parsing the path provided. 

Can you confirm the code in the README is not working on your computer ? 

What is the error you got when trying to run 

``` r
library(craneur)
colin <- Craneur$new("Colin")
colin$add_package("../craneur_0.0.0.9000.tar.gz") # your package here, of course :) 
colin$write(path = ".")
``` 

Thanks for you help, really appreciated :) 

C.

**Comment by EmilHvitfeldt** [comment]
Ohh sorry! I must have been on a earlier version without realising! Everything seems to run smoothly after a fresh install from github :)

**Comment by ColinFay** [comment]
No pblm :) 

Cheers!

**Pull request merged**
